"""
middleware/rate_limit.py — slowapi rate-limiter configuration.

Uses in-memory storage (no Redis required).  This is appropriate for a
single-instance deployment on Render free tier.  If you scale to multiple
instances, switch to a Redis-backed backend.

Rate limits are applied **only** to ``POST /api/simulate`` — all other
endpoints (tickers, validate-ticker, health) are unrestricted.

Two tiers:
  - **Guest** (no auth header): ``3/hour``, keyed by client IP
  - **Authenticated** (valid JWT): ``20/hour``, keyed by user ID
"""

import logging

from slowapi import Limiter
from slowapi.util import get_remote_address
from starlette.requests import Request

from config import AUTH_MAX_SIMULATIONS_PER_HOUR, GUEST_MAX_SIMULATIONS_PER_HOUR

# ---------------------------------------------------------------------------
# Module-level logger
# ---------------------------------------------------------------------------

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Key function — decides what to rate-limit by
# ---------------------------------------------------------------------------


def get_rate_limit_key(request: Request) -> str:
    """
    Return a rate-limit key for the current request.

    If the request carries an authenticated user (attached to
    ``request.state.user`` by the auth middleware in ``main.py``),
    key by the user's ID so that their limit is per-account.

    Otherwise, fall back to the client's IP address.
    """
    user = getattr(request.state, "user", None)
    if user and getattr(user, "is_authenticated", False):
        return f"user:{user.user_id}"
    return get_remote_address(request)


# ---------------------------------------------------------------------------
# Dynamic limit string — returns different rate for guest vs auth
# ---------------------------------------------------------------------------


def get_dynamic_limit(key: str) -> str:
    """
    Return the rate-limit string for the current request based on the
    caller's tier, by inspecting the key generated by get_rate_limit_key.

    Examples: ``"3/hour"`` for guests, ``"20/hour"`` for authenticated users.
    """
    if key.startswith("user:"):
        return f"{AUTH_MAX_SIMULATIONS_PER_HOUR}/hour"
    return f"{GUEST_MAX_SIMULATIONS_PER_HOUR}/hour"


# ---------------------------------------------------------------------------
# Limiter instance — import this in main.py and routers
# ---------------------------------------------------------------------------

limiter = Limiter(
    key_func=get_rate_limit_key,
    default_limits=[],          # No global default — limits are per-endpoint
    storage_uri="memory://",    # In-memory (single instance)
)
